/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'primary-container': '#0052cc',
        'error-container': '#ffdad6',
        'tertiary-container': '#a33500',
        'surface-variant': '#e1e2ec',
        'tertiary-fixed-dim': '#ffb59b',
        'tertiary-fixed': '#ffdbcf',
        'on-background': '#191b23',
        'secondary-fixed': '#dee2f3',
        'tertiary': '#7b2600',
        'on-secondary-fixed': '#161b27',
        'on-surface': '#191b23',
        'secondary': '#595e6c',
        'primary-fixed': '#dae2ff',
        'surface-container': '#ededf8',
        'inverse-surface': '#2e3038',
        'on-primary-container': '#c4d2ff',
        'on-secondary-fixed-variant': '#424754',
        'secondary-container': '#dee2f3',
        'primary-fixed-dim': '#b2c5ff',
        'surface-tint': '#0c56d0',
        'surface-container-lowest': '#ffffff',
        'background': '#faf8ff',
        'on-secondary': '#ffffff',
        'outline': '#737685',
        'inverse-on-surface': '#f0f0fb',
        'inverse-primary': '#b2c5ff',
        'secondary-fixed-dim': '#c2c6d6',
        'outline-variant': '#c3c6d6',
        'surface-dim': '#d9d9e4',
        'on-surface-variant': '#434654',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001848',
        'surface': '#faf8ff',
        'on-tertiary-fixed': '#380d00',
        'surface-container-high': '#e7e7f2',
        'surface-bright': '#faf8ff',
        'surface-container-low': '#f3f3fd',
        'on-tertiary-container': '#ffc6b2',
        'on-secondary-container': '#5f6472',
        'on-primary-fixed-variant': '#0040a2',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#812800',
        'surface-container-highest': '#e1e2ec',
        'primary': '#003d9b',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'critical-alert': '#ba1a1a',
        'critical-bg': '#ffdad6',
        'warning-alert': '#a33500',
        'warning-bg': '#ffdbcf',
        'info-alert': '#0052cc',
        'info-bg': '#c4d2ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        gutter: '16px',
        base: '4px',
        'container-margin': '24px',
        md: '16px',
        xl: '32px',
        sm: '12px',
        xs: '8px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'data-mono': ['monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
